trigger:
- main

pool:
  name: 'Default'

variables:
  # Azure DevOps -> Project Settings -> Service Connections-la neenga kudutha EXACT name-ah inga kudunga
  dockerRegistryServiceConnection: 'MyACRConnection' 
  kubernetesServiceConnection: 'MyAKSConnection'
  
  imageRepository: 'bank-api'
  # IDHU DHAAN MUKKIAM: Correct ACR Login Server
  containerRegistry: 'citibankreg31318.azurecr.io' 
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Stage'
  jobs:
  - job: Build
    displayName: 'Build on Local Agent'
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: $(dockerRegistryServiceConnection)

    - task: Docker@2
      displayName: 'Build and Push image'
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: DeployToAKS
  displayName: 'Deploy Stage'
  dependsOn: BuildAndPush
  jobs:
  - job: Deploy
    displayName: 'Deploy to AKS'
    steps:
    - task: KubernetesManifest@0
      displayName: 'Deploy to AKS'
      inputs:
        action: 'deploy'
        namespace: 'bank-api-namespace'
        manifests: '$(Build.SourcesDirectory)/deployment.yaml'
        # Inga $(tag) use pannradhu dhaan best practice
        containers: '$(containerRegistry)/$(imageRepository):$(tag)'
        kubernetesServiceConnection: $(kubernetesServiceConnection)
