trigger:
- main

pool:
  vmImage: 'ubuntu-latest' # Standard Microsoft-hosted agent use pannunga

variables:
  dockerRegistryServiceConnection: 'MyACRConnection'
  imageRepository: 'bank-api'
  containerRegistry: 'citibankreg31318.azurecr.io'
  tag: '$(Build.BuildId)'

stages:
# STAGE 1: Build Once
- stage: BuildAndPush
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

# STAGE 2: Deploy to West US (Primary)
- stage: DeployToWestUS
  dependsOn: BuildAndPush
  jobs:
  - deployment: Deploy
    environment: 'citi-westus'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'sc-citi-westus-dr' # West US Connection
              namespace: 'citi-dr-app'
              manifests: '$(Build.SourcesDirectory)/deployment.yaml'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'

# STAGE 3: Deploy to Central India (DR)
- stage: DeployToCentralIndia
  dependsOn: DeployToWestUS 
  jobs:
  - deployment: Deploy
    environment: 'citi-centralindia'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            inputs:
              action: 'deploy'
              kubernetesServiceConnection: 'sc-citi-centralindia-dr' # Central India Connection
              namespace: 'citi-dr-app'
              manifests: '$(Build.SourcesDirectory)/deployment.yaml'
              containers: '$(containerRegistry)/$(imageRepository):$(tag)'
