apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-service
  namespace: bank-api-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
      - name: bank-api
        image: citibankacr.azurecr.io/bank-api:latest # Unga ACR name 'citibankacr' thaana-nu check pannikonga
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api-service
  namespace: bank-api-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bank-api
