apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-service
  namespace: bank-api-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          # Inga dhaan change pannanum: 'citibankacr' lendhu 'citibankreg31318'-ku maathunga
          image: citibankreg31318.azurecr.io/bank-api:latest 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api-service
  namespace: bank-api-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bank-api
