apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api-service
  namespace: citi-dr-app  # <--- Change this if you used citi-dr-app before
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: citibankreg31318.azurecr.io/bank-api:latest 
          ports:
            - containerPort: 8080
          env:
            - name: REGION_NAME
              value: "DR Setup" # Namma Java code-ku idhu help-aa irukum
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api-service
  namespace: citi-dr-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: bank-api
